services:
  weather-server:
    build:
      context: ./
      dockerfile: ./weather-server/Dockerfile  
    ports:
      - "${ROCKET_PORT}:${ROCKET_PORT}" 
    environment:
      - IS_CONTAINER=true
      - WEATHER_MICROSERVICE_URL=http://weather-microservice
    networks:
      - weather-network
    env_file:
      - .env

  weather-microservice:
    build:
      context: ./
      dockerfile: ./weather-micro/Dockerfile    
    ports:
      - "${WEATHER_MICROSERVICE_PORT}:${WEATHER_MICROSERVICE_PORT}" 
    networks:
      - weather-network
    env_file:
      - .env

networks:
  weather-network:
    driver: bridge
    