services:
  weather-server:
    build:
      context: ./
      dockerfile: ./weather-server/Dockerfile  
    ports:
      - "8000:8000" 
    environment:
      - IS_CONTAINER=true
    networks:
      - weather-network
    env_file:
      - .env

  weather-microservice:
    build:
      context: ./
      dockerfile: ./weather-micro/Dockerfile    
    ports:
      - "8080:8080"
    networks:
      - weather-network
    env_file:
      - .env

networks:
  weather-network:
    driver: bridge
    