[package]
name = "weather-server"
version = "0.1.0"
edition = "2021"

[dependencies]
weather-utils = {path = "../weather-utils" }
hyper = { version = "1.5.2", features = ["full"] }
reqwest = "0.12.12"
rocket = "0.5.1"
dotenvy = "0.15.7"
